package rs.ac.bg.student.marko.MavenClientMuseum.form;

import java.net.SocketException;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import rs.ac.bg.student.marko.MavenClientMuseum.controller.ClientController;
import rs.ac.bg.student.marko.MavenClientMuseum.form.eksponat.NewEksponatForm;
import rs.ac.bg.student.marko.MavenClientMuseum.form.eksponat.SearchEksponatForm;
import rs.ac.bg.student.marko.MavenClientMuseum.form.izlozba.NewIzlozbaForm;
import rs.ac.bg.student.marko.MavenClientMuseum.form.izlozba.SearchIzlozbaForm;
import rs.ac.bg.student.marko.MavenClientMuseum.form.kustos.NewKustosForm;
import rs.ac.bg.student.marko.MavenClientMuseum.form.kustos.SearchKustosForm;
import rs.ac.bg.student.marko.MavenClientMuseum.form.stalnaPostavka.NewStalnaPostavkaForm;
import rs.ac.bg.student.marko.MavenClientMuseum.form.stalnaPostavka.SearchStalnaPostavkaForm;
import rs.ac.bg.student.marko.MavenClientMuseum.session.Session;
import rs.ac.bg.student.marko.MavenCommonMuseum.domain.Eksponat;
import rs.ac.bg.student.marko.MavenCommonMuseum.domain.Izlozba;
import rs.ac.bg.student.marko.MavenCommonMuseum.domain.StalnaPostavka;

public class MainForm extends javax.swing.JFrame {

    public MainForm() {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        lblTrenutnoUlogovani.setText(Session.getInstance().getTrenutnoUlogovani().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblTrenutnoUlogovani = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuEksponat = new javax.swing.JMenu();
        menuItemNoviEksponat = new javax.swing.JMenuItem();
        menuItemPretragaEksponata = new javax.swing.JMenuItem();
        menuIzlozba = new javax.swing.JMenu();
        menuItemNovaIzlozba = new javax.swing.JMenuItem();
        menuItemPretragaIzlozba = new javax.swing.JMenuItem();
        menuKustos = new javax.swing.JMenu();
        menuItemNoviKustos = new javax.swing.JMenuItem();
        menuItemPretragaKustosa = new javax.swing.JMenuItem();
        menuStalnaPostavka = new javax.swing.JMenu();
        menuItemNovaStalnaPostavka = new javax.swing.JMenuItem();
        menuItemPretragaStalnihPostavka = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusCycleRoot(false);

//        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("../MavenClientMuseum/rs/ac/bg/student/marko/MavenClientMuseum/img/museum_picture.jpg"))); // NOI18N
//        jLabel1.setMinimumSize(new java.awt.Dimension(640, 360));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ulogovani korisnik"));

        lblTrenutnoUlogovani.setForeground(new java.awt.Color(0, 0, 51));
        lblTrenutnoUlogovani.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(593, Short.MAX_VALUE)
                .addComponent(lblTrenutnoUlogovani, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblTrenutnoUlogovani)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        menuEksponat.setText("Eksponat");

        menuItemNoviEksponat.setText("Novi eksponat");
        menuItemNoviEksponat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNoviEksponatActionPerformed(evt);
            }
        });
        menuEksponat.add(menuItemNoviEksponat);

        menuItemPretragaEksponata.setText("Pretraga eksponata");
        menuItemPretragaEksponata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPretragaEksponataActionPerformed(evt);
            }
        });
        menuEksponat.add(menuItemPretragaEksponata);

        jMenuBar1.add(menuEksponat);

        menuIzlozba.setText("Izložba");

        menuItemNovaIzlozba.setText("Nova izložba");
        menuItemNovaIzlozba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNovaIzlozbaActionPerformed(evt);
            }
        });
        menuIzlozba.add(menuItemNovaIzlozba);

        menuItemPretragaIzlozba.setText("Pretraga izložbi");
        menuItemPretragaIzlozba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPretragaIzlozbaActionPerformed(evt);
            }
        });
        menuIzlozba.add(menuItemPretragaIzlozba);

        jMenuBar1.add(menuIzlozba);

        menuKustos.setText("Kustos");

        menuItemNoviKustos.setText("Novi kustos");
        menuItemNoviKustos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNoviKustosActionPerformed(evt);
            }
        });
        menuKustos.add(menuItemNoviKustos);

        menuItemPretragaKustosa.setText("Pretraga kustosa");
        menuItemPretragaKustosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPretragaKustosaActionPerformed(evt);
            }
        });
        menuKustos.add(menuItemPretragaKustosa);

        jMenuBar1.add(menuKustos);

        menuStalnaPostavka.setText("Stalna postavka");

        menuItemNovaStalnaPostavka.setText("Nova stalna postavka");
        menuItemNovaStalnaPostavka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNovaStalnaPostavkaActionPerformed(evt);
            }
        });
        menuStalnaPostavka.add(menuItemNovaStalnaPostavka);

        menuItemPretragaStalnihPostavka.setText("Pretraga stalnih postavki");
        menuItemPretragaStalnihPostavka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPretragaStalnihPostavkaActionPerformed(evt);
            }
        });
        menuStalnaPostavka.add(menuItemPretragaStalnihPostavka);

        jMenuBar1.add(menuStalnaPostavka);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void menuItemNoviEksponatActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        new NewEksponatForm(this, rootPaneCheckingEnabled, new Eksponat(), FormEnum.NOVI).setVisible(true);
    }                                                    

    private void menuItemPretragaEksponataActionPerformed(java.awt.event.ActionEvent evt) {                                                          
        new SearchEksponatForm(this, rootPaneCheckingEnabled).setVisible(true);
    }                                                         

    private void menuItemNovaIzlozbaActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        new NewIzlozbaForm(this, rootPaneCheckingEnabled, FormEnum.NOVI, new Izlozba()).setVisible(true);
    }                                                   

    private void menuItemNoviKustosActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        new NewKustosForm(this, rootPaneCheckingEnabled, FormEnum.NOVI, null).setVisible(true);
    }                                                  

    private void menuItemPretragaKustosaActionPerformed(java.awt.event.ActionEvent evt) {                                                        
        new SearchKustosForm(this, rootPaneCheckingEnabled).setVisible(true);
    }                                                       

    private void menuItemPretragaIzlozbaActionPerformed(java.awt.event.ActionEvent evt) {                                                        
        new SearchIzlozbaForm(this, rootPaneCheckingEnabled).setVisible(true);
    }                                                       

    private void menuItemNovaStalnaPostavkaActionPerformed(java.awt.event.ActionEvent evt) {                                                           
        new NewStalnaPostavkaForm(this, rootPaneCheckingEnabled, new StalnaPostavka(), FormEnum.NOVI).setVisible(true);
    }                                                          

    private void menuItemPretragaStalnihPostavkaActionPerformed(java.awt.event.ActionEvent evt) {                                                                
        new SearchStalnaPostavkaForm(this, rootPaneCheckingEnabled).setVisible(true);
    }                                                               


    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTrenutnoUlogovani;
    private javax.swing.JMenu menuEksponat;
    private javax.swing.JMenuItem menuItemNovaIzlozba;
    private javax.swing.JMenuItem menuItemNovaStalnaPostavka;
    private javax.swing.JMenuItem menuItemNoviEksponat;
    private javax.swing.JMenuItem menuItemNoviKustos;
    private javax.swing.JMenuItem menuItemPretragaEksponata;
    private javax.swing.JMenuItem menuItemPretragaIzlozba;
    private javax.swing.JMenuItem menuItemPretragaKustosa;
    private javax.swing.JMenuItem menuItemPretragaStalnihPostavka;
    private javax.swing.JMenu menuIzlozba;
    private javax.swing.JMenu menuKustos;
    private javax.swing.JMenu menuStalnaPostavka;
    // End of variables declaration                   
}
