package rs.ac.bg.student.marko.MavenClientMuseum.form.eksponat;

import java.net.SocketException;
import java.util.List;

import javax.swing.JOptionPane;

import rs.ac.bg.student.marko.MavenClientMuseum.controller.ClientController;
import rs.ac.bg.student.marko.MavenClientMuseum.form.FormEnum;
import rs.ac.bg.student.marko.MavenCommonMuseum.domain.Eksponat;
import rs.ac.bg.student.marko.MavenCommonMuseum.domain.StalnaPostavka;
import rs.ac.bg.student.marko.MavenCommonMuseum.domain.TipEksponata;

public class NewEksponatForm extends javax.swing.JDialog {

    private FormEnum formEnum;
    private Eksponat eksponat;

    public NewEksponatForm(java.awt.Frame parent, boolean modal, Eksponat eksponat, FormEnum formEnum) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.formEnum = formEnum;
        this.eksponat = eksponat;
        try {
            cmbTipEksponata.removeAllItems();
            List<TipEksponata> list = ClientController.getInstance().getAllTipoviEksponata();

            for (TipEksponata tipEksponata : list) {
                cmbTipEksponata.addItem(tipEksponata);
            }

            cmbStalnaPostavka.removeAllItems();
            List<StalnaPostavka> list2 = ClientController.getInstance().getAllStalnePostavke();

            for (StalnaPostavka stalnaPostavka : list2) {
                cmbStalnaPostavka.addItem(stalnaPostavka);
            }

            if (this.formEnum.equals(formEnum.IZMENA)) {
                this.eksponat = eksponat;
                txtNazivEksponata.setText(eksponat.getNazivEksponata());
                txtNazivEksponata.setEditable(false);
                txtVisina.setText(Double.toString(eksponat.getVisina()));
                txtTezina.setText(Double.toString(eksponat.getTezina()));
                txtStarost.setText(eksponat.getStarost());
                cmbTipEksponata.setSelectedItem(eksponat.getTipEksponata());                
                cmbStalnaPostavka.setSelectedItem(eksponat.getStalnaPostavka());

            }
        } catch (Exception ex) {
            ex.printStackTrace();
            if (ex instanceof SocketException) {
                JOptionPane.showMessageDialog(this, "Server je prekinuo komunikaciju", "Greska", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
            }
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        txtNazivEksponata = new javax.swing.JTextField();
        txtVisina = new javax.swing.JTextField();
        txtTezina = new javax.swing.JTextField();
        btnSacuvaj = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cmbTipEksponata = new javax.swing.JComboBox<>();
        cmbStalnaPostavka = new javax.swing.JComboBox<>();
        txtStarost = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Naziv eksponata:");

        jLabel2.setText("Visina (cm):");

        jLabel3.setText("Tezina (kg):");

        jLabel4.setText("Starost:");

        jLabel5.setText("Stalna postavka:");

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        jLabel7.setText("Tip eksponata:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbTipEksponata, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTezina)
                            .addComponent(txtVisina)
                            .addComponent(cmbStalnaPostavka, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNazivEksponata, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtStarost)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 308, Short.MAX_VALUE)
                        .addComponent(btnSacuvaj)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNazivEksponata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtVisina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTezina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtStarost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(cmbTipEksponata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbStalnaPostavka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnSacuvaj))
                .addGap(0, 21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {                                          
        this.dispose();
    }                                         

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {                                           
        try {
            String naziv = txtNazivEksponata.getText();
            if (naziv.isEmpty()) {
                throw new Exception("Niste uneli naziv eksponata");
            }
           
            String visinaText = txtVisina.getText();
            if (visinaText.isEmpty()) {
                throw new Exception("Niste uneli visinu eksponata");
            }
            Double visina=Double.parseDouble(visinaText);
            
            String tezinaText = txtTezina.getText();
            if (tezinaText.isEmpty()) {
                throw new Exception("Niste uneli tezinu eksponata");
            }
            Double tezina=Double.parseDouble(tezinaText);
            
            String starost = txtStarost.getText();
            if (starost.isEmpty()) {
                throw new Exception("Niste uneli starost eksponata");
            }
            
            TipEksponata tipEksponata = (TipEksponata) cmbTipEksponata.getSelectedItem();
            StalnaPostavka stalnaPostavka = (StalnaPostavka) cmbStalnaPostavka.getSelectedItem();

            eksponat.setNazivEksponata(naziv);
            eksponat.setVisina(visina);
            eksponat.setTezina(tezina);
            eksponat.setStarost(starost);
            eksponat.setTipEksponata(tipEksponata);
            eksponat.setStalnaPostavka(stalnaPostavka);

            if (formEnum.equals(formEnum.NOVI)) {
                ClientController.getInstance().saveEksponat(eksponat);
                JOptionPane.showMessageDialog(this, "Uspesno ste sacuvali nov eksponat");
            } else {
                ClientController.getInstance().editEksponat(eksponat);
                JOptionPane.showMessageDialog(this, "Uspesno ste izmenili eksponat");
            }
            this.dispose();
        } catch (Exception ex) {
            ex.printStackTrace();
            if (ex instanceof SocketException) {
                JOptionPane.showMessageDialog(this, "Server vam je prekinuo komunikaciju! Gasenje programa...", "Greska", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
            }if(ex instanceof NumberFormatException){
                JOptionPane.showMessageDialog(this, "Niste ispravno uneli visinu ili tezinu. Mogu se uneti samo brojevi");
            }else
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }                                          


    // Variables declaration - do not modify                     
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox<Object> cmbStalnaPostavka;
    private javax.swing.JComboBox<Object> cmbTipEksponata;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtNazivEksponata;
    private javax.swing.JTextField txtStarost;
    private javax.swing.JTextField txtTezina;
    private javax.swing.JTextField txtVisina;
    // End of variables declaration                   
}

