package rs.ac.bg.student.marko.MavenClientMuseum.form.stalnaPostavka;

import java.net.SocketException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

import javax.swing.JOptionPane;

import rs.ac.bg.student.marko.MavenClientMuseum.controller.ClientController;
import rs.ac.bg.student.marko.MavenClientMuseum.form.FormEnum;
import rs.ac.bg.student.marko.MavenCommonMuseum.domain.Kustos;
import rs.ac.bg.student.marko.MavenCommonMuseum.domain.StalnaPostavka;

public class NewStalnaPostavkaForm extends javax.swing.JDialog {

    private FormEnum formEnum;
    private StalnaPostavka stalnaPostavka;

    public NewStalnaPostavkaForm(java.awt.Frame parent, boolean modal, StalnaPostavka stalnaPostavka, FormEnum formEnum) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.formEnum = formEnum;
        this.stalnaPostavka = stalnaPostavka;
        try {
            cmbKustos.removeAllItems();
            List<Kustos> list = ClientController.getInstance().getAllKustosi();

            for (Kustos kustos : list) {
                cmbKustos.addItem(kustos);
            }
            if (formEnum.equals(FormEnum.IZMENA)) {
                SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
                this.stalnaPostavka = stalnaPostavka;
                txtNazivPostavke.setText(stalnaPostavka.getNazivPostavke());
                txtDatumFormiranja.setText(sdf.format(stalnaPostavka.getDatumFormiranja()));
                cmbKustos.setSelectedItem(stalnaPostavka.getKustos());

            }
        } catch (Exception ex) {
            if (ex instanceof SocketException) {
                JOptionPane.showMessageDialog(this, "Server je prekinuo komunikaciju", "Greska", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
            }
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        txtNazivPostavke = new javax.swing.JTextField();
        btnSacuvaj = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDatumFormiranja = new javax.swing.JFormattedTextField();
        cmbKustos = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Naziv postavke:");

        jLabel4.setText("Datum formiranja:");

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        txtNazivPostavke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNazivPostavkeActionPerformed(evt);
            }
        });

        btnSacuvaj.setText("Sačuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        jLabel7.setText("Kustos:");

        jLabel6.setText("Datume unosite u formatu dd.MM.yyyy");

        txtDatumFormiranja.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd.MM.yyyy"))));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(249, 253, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCancel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSacuvaj))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtNazivPostavke)
                                    .addComponent(txtDatumFormiranja)
                                    .addComponent(cmbKustos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNazivPostavke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDatumFormiranja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbKustos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSacuvaj)
                    .addComponent(btnCancel))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {                                          
        this.dispose();
    }                                         

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {                                           
        try {
            String nazivPostavke = txtNazivPostavke.getText();
            if (nazivPostavke.isEmpty()) {
                throw new Exception("Niste uneli naziv postavke");
            }
            String datumFormiranjaText = txtDatumFormiranja.getText();
            if (datumFormiranjaText.isEmpty()) {
                throw new Exception("Niste uneli datum formiranja");
            }
            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
            Date datumFormiranjaDate = sdf.parse(datumFormiranjaText);
            if(datumFormiranjaDate.before(new Date()) && formEnum.equals(FormEnum.NOVI))
                throw new Exception("Datum formiranja mora biti neki buduci datum");
            
            Kustos kustos=(Kustos) cmbKustos.getSelectedItem();
                
            stalnaPostavka.setNazivPostavke(nazivPostavke);
            stalnaPostavka.setDatumFormiranja(datumFormiranjaDate);
            stalnaPostavka.setKustos(kustos);
         
            if (formEnum.equals(FormEnum.NOVI)) {
                stalnaPostavka.setBrojEksponata(0);
                ClientController.getInstance().saveStalnaPostavka(stalnaPostavka);
                JOptionPane.showMessageDialog(this, "Uspesno ste sacuvali novu stalnu postavku");
            } else {
                ClientController.getInstance().editStalnaPostavka(stalnaPostavka);
                JOptionPane.showMessageDialog(this, "Uspesno ste izmenili stalnu postavku");
            }
            this.dispose();
        } catch (Exception ex) {
            ex.printStackTrace();
            if (ex instanceof SocketException) {
                JOptionPane.showMessageDialog(this, "Server vam je prekinuo komunikaciju! Gasenje programa...", "Greska", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
            }
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }                                          

    private void txtNazivPostavkeActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                


    // Variables declaration - do not modify                     
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox<Object> cmbKustos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JFormattedTextField txtDatumFormiranja;
    private javax.swing.JTextField txtNazivPostavke;
    // End of variables declaration                   
}
