package rs.ac.bg.student.marko.MavenClientMuseum.form.kustos;

import java.awt.Frame;
import java.net.SocketException;
import java.util.List;

import javax.swing.JOptionPane;

import rs.ac.bg.student.marko.MavenClientMuseum.controller.ClientController;
import rs.ac.bg.student.marko.MavenClientMuseum.form.FormEnum;
import rs.ac.bg.student.marko.MavenCommonMuseum.domain.Kustos;

public class SearchKustosForm extends javax.swing.JDialog {

    private TableModelKustos tableModelKustos ;
    public SearchKustosForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTableModel();
        
    }
    
    private void setTableModel(){
        try {
            List<Kustos> list = ClientController.getInstance().getAllKustosi();
            tableModelKustos = new TableModelKustos(list);
            tblKustosi.setModel(tableModelKustos);
        } catch (Exception ex) {
            if (ex instanceof SocketException) {
                JOptionPane.showMessageDialog(this, "Server je prekinuo komunikaciju", "Greska", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
            }
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblKustosi = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtPretraga = new javax.swing.JTextField();
        btnIzmeni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblKustosi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblKustosi);

        jLabel1.setText("Pretraga:");

        txtPretraga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPretragaKeyReleased(evt);
            }
        });

        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtPretraga)
                        .addGap(18, 18, 18)
                        .addComponent(btnIzmeni)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIzmeni))
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>                        

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {                                          
        int row = tblKustosi.getSelectedRow();
        if (row > -1) {
            Kustos kustos = tableModelKustos.getSelected(row);
            new NewKustosForm((Frame) this.getParent(), rootPaneCheckingEnabled, FormEnum.IZMENA, kustos).setVisible(true);
            this.dispose();
        }
    }                                         

    private void txtPretragaKeyReleased(java.awt.event.KeyEvent evt) {                                        
        try {
            String param = txtPretraga.getText().trim();
            List<Kustos> list;
            if (param.isEmpty()) {
                list = ClientController.getInstance().getAllKustosi();
            } else {
                list = ClientController.getInstance().searchKustosi(param);
            }
            tableModelKustos = new TableModelKustos(list);
            tblKustosi.setModel(tableModelKustos);
        } catch (Exception ex) {
            if (ex instanceof SocketException) {
                JOptionPane.showMessageDialog(this, "Server je prekinuo komunikaciju", "Greska", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
            }
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }                                       


    // Variables declaration - do not modify                     
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKustosi;
    private javax.swing.JTextField txtPretraga;
    // End of variables declaration                   
}